networks:
  internal:
    driver: bridge

volumes:
  mysql-storage:
    driver: local

services:
  mysql:
    image: mysql:8.0
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: unless-stopped
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tasks-api
    volumes:
      - mysql-storage:/var/lib/mysql:rw
    ports:
      - 3306:3306
    networks:
      - internal
